" Originally from: https://dougblack.io/words/a-good-vimrc.html

" Don't put any lines in your vimrc that you don't understand.
" Don't put any lines in your vimrc that you don't understand.
" Don't put any lines in your vimrc that you don't understand.

" Vim, not Vi {{{
" Don't try to be vi compatible
set nocompatible
" }}}
" Vim Plug {{{
" Note: To install, do this:
"       curl -fLo ~/.vim/autoload/plug.vim --create-dir https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" Note: Once installed, to install plugins, from within Vim, do this:
"       :PlugInstall
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-commentary'     " Toggle comments with commands like gc gcc gcgc
Plug 'kien/ctrlp.vim'           " Fuzzy finder
Plug 'flazz/vim-colorschemes'   " Tons of colorschemes
call plug#end()
" }}}
" Colors {{{
syntax enable           " enable syntax processing
"colorscheme evening    " This colorscheme included with Vim.
colorscheme badwolf     " This colorscheme available via plugin.
set termguicolors
" }}}
" Text Rendering {{{
set wrap                " Enable line wrapping.
set linebreak           " Avoid wrapping a line in the middle of a word.
" }}}
" Spaces & Tabs & Indent {{{
set tabstop=4           " 4 space tab
set expandtab           " use spaces for tabs
set softtabstop=4       " 4 space tab
set shiftwidth=4        " 4 space indentations
set shiftround          " When shifting lines, round the indentation to the nearest multiple of “shiftwidth.”
set modelines=10        " Allow putting a modeline (e.g. "# vim:set expandtab tabstop=4 softtabstop=4 shiftwidth=14:") within the first or last 10 lines of a file.
filetype on             " Turn on filetype detection                - see https://vi.stackexchange.com/a/10125
filetype plugin on      " Turn on filetype specific plugins         - see https://vi.stackexchange.com/a/10125
filetype indent on      " Turn on filetype specific indentations    - see https://vi.stackexchange.com/a/10125
set autoindent          " Turn on auto indentation.
" }}}
" UI Layout {{{
set number              " show line numbers
set showcmd             " show command in bottom bar (right side) - basically just shows what you're typing...
set cursorline          " highlight current line
set wildmenu            " on second to bottom line, shows partial tab completion when tab-completing files in :ex
set showmatch           " higlight matching parenthesis
set laststatus=2        " Always display the status bar (2nd to last line)
set ruler               " Always show cursor position (in status bar)
set mouse=a             " Enable mouse for scrolling and resizing.
set title               " Set the window’s title, reflecting the file currently being edited.
" }}}
" Problematic Characters {{{
set fileformats=unix                    " We want to display MS Windows carriage returns as ^M if they are present, as they are problematic. Needs to go before 'set list'.
set list                                " See (some) hidden characters (see next line).
set listchars=tab:›\ ,extends:#,nbsp:.  " Highlight problematic whitespace characters.
" }}}
" Performance {{{
set complete-=i         " Limit the files searched for auto-completes.
set lazyredraw          " Don’t update screen during macro and script execution.
" }}}
" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight all matches
set ignorecase          " ignore case when searching
set smartcase           " Automatically switch search to case-sensitive when search query contains an uppercase letter.
" }}}
" Folding {{{
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set nofoldenable        " don't fold files by default on open
"nnoremap <space> za
"set foldlevelstart=10   " start with fold level of 1
" }}}
" Line Shortcuts {{{
"nnoremap j gj           " in wrap mode, don't skip over wrapped portion of lines while navigating
"nnoremap k gk           " in wrap mode, don't skip over wrapped portion of lines while navigating
"nnoremap gV `[v`]       " highlight last inserted text
" }}}
" Misc {{{
" Remove trailing whitespace on save
autocmd BufWritePre * :%s/\s+$//e
" }}}

" vim:set expandtab tabstop=4 softtabstop=4 shiftwidth=4 foldenable foldmethod=marker foldlevel=0:
