# bashrc is for non-interactive shells

# shortcut to this dotfiles path is $DOTFILES
export DOTFILES="$HOME/.dotfiles"

# /etc/profile workaround - MUST BE (NEARLY) THE FIRST LINE IN THIS FILE!
if [ -f $DOTFILES/etc_profile_workaround ]; then
    source $DOTFILES/etc_profile_workaround
fi

# Never put anything in your bashrc that you don't understand.
# Never put anything in your bashrc that you don't understand.
# Never put anything in your bashrc that you don't understand.

# Source the non-interactive file
source $DOTFILES/all/main-non-interactive

# Load bash settings.
source $DOTFILES/bash/settings

# Load source files.
for f in $DOTFILES/*/source ; do source "$f" ; done

# THE LAST ITEMS BELOW.
#
# Miniconda 3 - This should be the LAST item in your bash_proile.
source $DOTFILES/conda/setup_bash
# Nix
source $DOTFILES/nix/setup_bash

# Lando
export PATH="/Users/sydes/.lando/bin${PATH+:$PATH}" #landopath

# Atuin
source "$HOME/.atuin/bin/env"

[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
eval "$(atuin init bash --disable-up-arrow)"

# Prompt.
# Yes, inside bashrc (non-interactive), not bash_profile (interactive).
# For whatever reason, 'sudo bash' won't load bash_profile, only bashrc.
# All of these incantations do *not* work:
#       sudo bash
#       sudo -E bash
#       sudo -i bash  (i.e., sudo --login bash)
# But putting the prompt here in bashrc *does* work, so that's what I'll do. 🤷
# And, noted, putting it here doesn't seem to interfere with scp. 
eval "$(starship init bash)"

